name: CI

on:
  pull_request:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run lint:scss
      - run: npm run prebuild
